# Generated by Django 5.0.4 on 2024-04-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
