# Generated by Django 5.0.4 on 2024-04-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_app', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
    ]
